### ISSUE TITLE
TODO: vignette to assess this backend

### ISSUE THREAD

**Issue by lgatto** [rformassspectrometry/MsBackendSql#1]
I think it would be useful to have a short vignette assessing the `MsBackendSqlDb` and `MsBackendMzR` (I don't think a benchmark against `MsBackendDataFrame` is relevant).

@jorainer: I asked @plantton to do something along the lines of the vignette we shared with you last week. Let him know if you have ideas.

**Comment by jorainer** [comment]
Makes total sense to me. In addition to memory demand I would however also include a `microbenchmark` for some of typical operations:
- Import data
- extract m/z values for the whole data
- get retention times for the whole data
- subset the backend to x random spectra and extract m/z values
- subset the backend to x random spectra and extract retention times

**Comment by lgatto** [comment]
To be able to do these tests, we would need to following implementations for the backend:
- `$` accessor, using the `.get_db_data` function
- `[` accessor, to subset the data by indices
- `filterMsLevel()` as an example of an optimised row filter function.

**Comment by jorainer** [comment]
For a reference implementation (to use as sort of a template) I would use the `MsBackendDataFrame` - that backend has all methods implemented.

**Comment by lgatto** [comment]
I think we will want two comparisons/benchmarks
- against `MsBackendDataFrame` to check/assess functionality
- against `MsBackendMzR` to demonstrate reduced memory consumption (which is what lead to this development initially).
