### ISSUE TITLE
Bug in show,MsBackendSqlDb

### ISSUE THREAD

**Issue by lgatto** [rformassspectrometry/MsBackendSql#14]
An empty `MsBackendSqlDb` object should be initialised and shown properly
```r
> MsBackendSqlDb()
MsBackendSqlDb with spectra
Error in if (nrow(spd)) { : argument is of length zero
```

**Comment by lgatto** [comment]
This must also be tested in a unit test.

**Comment by plantton** [comment]
> This must also be tested in a unit test.

I will do it.

**Comment by plantton** [comment]
> An empty `MsBackendSqlDb` object should be initialised and shown properly
> 
> ```r
> > MsBackendSqlDb()
> MsBackendSqlDb with spectra
> Error in if (nrow(spd)) { : argument is of length zero
> ```

The current [validator](https://github.com/rformassspectrometry/MsBackendSql/blob/master/R/MsBackendSqlDb.R#L102-L107) will check:  
1. Whether there's a data table in SQLite database, i.e. `.valid_db_table_exists()`
2. Whether the data table contains necessary columns, i.e. `.valid_db_table_columns()`

I think if we want to initialise an empty `MsBackendSqlDb` object, I have to modify the validator.

**Comment by lgatto** [comment]
Two things:
- The error above is thrown by the `show` method, so that's not directly a problem with constructor. It could be addressed independently
- Given that there is (currently) no write support for the backend, creating an instance for an empty instance might not be relevant at this stage. Then, I suggest to handle this explicitly so that an error with a meaningful is thrown immediately.
