### ISSUE TITLE
Merging MsBackendSqlDb objects

### ISSUE THREAD

**Issue by lgatto** [rformassspectrometry/MsBackendSql#18]
When merging two objects, all the data should be conserved. Example:
```
DB1 with 10 records - rows: 1, 2, 3
DB2 with 10 records - rows, 5, 6
```
Merging this should generate something like
```
DB with 20 records - rows: 1, 2, 3, 15, 16
```
or 
```
DB1 with two tables of 10 records each - rows: 1, 2, 3 pointing to table1 and 5, 6, pointing to table2
```

**Comment by plantton** [comment]
I switched back the function of `.attach_migration` in commit [a9e84db](https://github.com/rformassspectrometry/MsBackendSql/pull/21/commits/a9e84db0f937dd1a448289555c5149292de677e7).

The current version is using the 1st solution:  
`DB with 20 records - rows: 1, 2, 3, 15, 16`.

The returning values, including the merged rows, are verified by [tests](https://github.com/plantton/MsBackendSql/blob/master/tests/testthat/test_MsBackendSqlDb-functions.R#L195-L259).
