### ISSUE TITLE
Reset row selection

### ISSUE THREAD

**Issue by lgatto** [rformassspectrometry/MsBackendSql#19]
We always have all records in the table and update the row indices upon filtering. For example
```
DB1 with 10 records, (selected) rows: 1, 2, 3
```
It would be useful to have a resetting function (for example `.reset_row_indices()`) that reverts the filters to get
```
DB1 with 10 records, (selected) rows: 1, 2, 3, ..., 10
```

**Comment by plantton** [comment]
The current commits will create a function to reset row selections.  

Currently, we only have reading functions and filtering/subsetting functions. The only exceptional function is the merging function which will attach two databases, and append a 2nd table to the first SQLite table (`modCount` slot will also be changed).  

So the reset function will fetch the number of rows from SQLite table, and use this value to re-create slot `rows`.

**Comment by lgatto** [comment]
Is this addressed? If so, please close the issue.

**Comment by plantton** [comment]
> Is this addressed? If so, please close the issue.

Looks like the permissions were off. It has been solved.
