### ISSUE TITLE
Subsetting functions of MsBackendSql

### ISSUE THREAD

**Issue by plantton** [rformassspectrometry/MsBackendSql#7]
The comparison between `MsBackendSql` and `MsBackendHdf5Peaks` demonstrates that `MsBackendSql` has potential to provide efficient I/O functionalities for metadata. So I want to create subsetting functionalities for `MsBackendSql`, which will involve selecting the relevant indices in a row index vector.

I also have an idea on the returning values: Some of the returned variables are too huge for a normal desktop, so is it possible to provide some preview information for the users, in case of really huge RAM consumption?

**Comment by lgatto** [comment]
- Regarding the vector of indices for subsetting, yes, this is needed. As fas as I can remember, this is also what is done in the `SQLDataFrame` - could you confirm. If so, it would be good to learn from what has been done there.

- I think it would also be useful to be able to reset any subsetting. This would essentially be a free operation, given that the data is still available.

- As for returning/displaying, please discuss this in a new issue, for clarify.

**Comment by lgatto** [comment]
I assume this can be closed - @plantton could you confirm.

**Comment by plantton** [comment]
> I assume this can be closed - @plantton could you confirm.

Indeed. This can be closed.
