### ISSUE TITLE
CI: github actions failing because mzR can't be built

### ISSUE THREAD

**Issue by sgibb** [rformassspectrometry/MsBackendSql#9]
`mzR` requires at least netcdf4. How to specify libnetcdf-dev or similar as dependency for all platforms?

**Comment by plantton** [comment]
I think just like using travis-ci, we have to append this dependency in GitHub Workflow.

**Comment by plantton** [comment]
I find a simple solution:
https://www.edwardthomson.com/blog/github_actions_14_conditionals_with_a_matrix.html

Will try to solve it tomorrow.

**Comment by plantton** [comment]
The following configurations can be used to check the package on all platforms:
https://github.com/plantton/MsBackendSql/blob/master/.github/workflows/check-standard.yaml

It seems the hosted runner for windows-latest has included netcdf. So I just added the netcdf library for the other 2 systems.

**Comment by sgibb** [comment]
@plantton great work! Just a minor change: IHMO it would be useful to use r devel instead of r 3.6

**Comment by plantton** [comment]
> @plantton great work! Just a minor change: IHMO it would be useful to use r devel instead of r 3.6

Do you mean use r 3.6 for all platforms?

**Comment by sgibb** [comment]
Yes, r devel for all platforms (honestly I don't care whether an unreleased package runs on an old version of R).
Maybe @jorainer prefers r 4? https://github.com/rformassspectrometry/MsBackendSql/pull/6/files#r436475176

**Comment by jorainer** [comment]
Actually, what I would suggest is to use `'release'` for Windows and for macOS and eventually `'release'` and `'devel'` for linux:

```
      matrix:
        config:
          - {os: windows-latest, r: 'release'}
          - {os: macOS-latest, r: 'release'}
          - {os: ubuntu-16.04, r: 'release', rspm: "https://demo.rstudiopm.com/all/__linux__/xenial/latest"}
          - {os: ubuntu-16.04-devel, r: 'devel', rspm: "https://demo.rstudiopm.com/all/__linux__/xenial/latest"}

```

Don't specifically look at the config/definition for ubuntu (i.e. if its xenial or so), just wanted to illustrate that I think it's sufficient to check the package for "R release" on all platforms and for one platform also the devel version.

**Comment by lgatto** [comment]
Definitely R >= 4.
